CREATE DATABASE [BD_BIBLIOTECANACIONAL]
GO
USE [BD_BIBLIOTECANACIONAL]
GO
CREATE TABLE TBL_ESTADO
(
	PK_CODIGO CHAR,
	NOMBRE VARCHAR(30) NOT NULL,
	NOMENCLATURA VARCHAR(5) NOT NULL,
	PRIMARY KEY(PK_CODIGO)
)

CREATE TABLE TBL_USUARIOS
(
	PK_ID BIGINT IDENTITY(1002235366,78),
	NOMBRES VARCHAR(100) NOT NULL,
	APELLIDOS VARCHAR(100) NOT NULL,
	CONTACTO VARCHAR(10) NOT NULL,
	DIRECCION VARCHAR(200) NOT NULL,
	CORREO VARCHAR(255) NOT NULL,
	FK_ESTADO CHAR NOT NULL,
	PRIMARY KEY(PK_ID),
	FOREIGN KEY(FK_ESTADO) REFERENCES [TBL_ESTADO](PK_CODIGO)
)
CREATE TABLE TBL_LIBROS
(
	PK_ISBN VARCHAR(12),
	NOMBRE VARCHAR(100) NOT NULL,
	AUTOR VARCHAR(50) NOT NULL,
	EDITORIAL VARCHAR(100) NOT NULL,
	FECHA_PUBLICACION DATE NOT NULL,
	FK_ESTADO CHAR NOT NULL,
	CANTIDAD_EJEMPLARES INT NOT NULL
	PRIMARY KEY(PK_ISBN),
	FOREIGN KEY(FK_ESTADO) REFERENCES [TBL_ESTADO](PK_CODIGO)
)
CREATE TABLE TBL_PRESTAMOS
(
	PK_NUMERO_PRESTAMO BIGINT IDENTITY(316491,1),
	FK_ID_USUARIOS BIGINT NOT NULL,
	FK_ISBN_LIBRO VARCHAR(12) NOT NULL,
	CANTIDAD INT NOT NULL,
	FECHA_REGISTRO DATE NOT NULL,
	FECHA_ENTREGA DATE NOT NULL,
	FK_ESTADO  CHAR NOT NULL,
	PRIMARY KEY(PK_NUMERO_PRESTAMO),
	FOREIGN KEY(FK_ID_USUARIOS) REFERENCES [TBL_USUARIOS](PK_ID),
	FOREIGN KEY(FK_ESTADO) REFERENCES [TBL_ESTADO](PK_CODIGO),
	FOREIGN KEY(FK_ISBN_LIBRO) REFERENCES [TBL_LIBROS](PK_ISBN)
)
------------------------------------------------------------------------------------------------
INSERT INTO [TBL_ESTADO](PK_CODIGO,NOMBRE,NOMENCLATURA)
VALUES
('1','DISPONIBLE','DSPNE'),
('2','NO DISPONIBLE','NDPNE'),
('3','SIN EXISTENCIAS','SEXAS'),
('4','ACTIVO','ACTVO'),
('5','INACTIVO','INATO'),
('6','SANCIONADO','SNCDO'),
('7','PRESTADO','PRSTO'),
('8','ENTREGADO','ENTGO')
SELECT * FROM [TBL_ESTADO]